# Generated by Django 3.1.1 on 2021-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentWord',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='wordlist',
        ),
    ]
