# Generated by Django 3.1.1 on 2021-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210218_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
