# Generated by Django 3.1.1 on 2021-02-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_mywordlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mywordlist',
            new_name='words',
        ),
    ]
